services:
  jackio:
    image: ghcr.io/vinip1250-art/jackio:latest  
    container_name: jackio
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "4000:4000"
    env_file:
      - .env
      environment:
      NODE_ENV: production
      DATA_FOLDER: /data
    volumes:
      - ./media:/data
